# bundle exec rubocop のみで両方実行されるようになる

require:
  - rubocop-rails
  - rubocop-rspec
# Missing frozen string literal comment.無効
Style/FrozenStringLiteralComment:
  Enabled: false
# Missing top-level class documentation comment.の推奨を非表示
Documentation:
  Enabled: false
# Method has too many linesの警告を無効
Metrics/MethodLength:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'lib/**/*'
# Align the keys of a hash literal if they span more than one lineの警告無効
Layout/HashAlignment:
  Exclude:
    - 'lib/**/*'